# Generated by Django 4.1.2 on 2022-12-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_image_alter_produto_preco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
